#!/usr/bin/env python3
"""Generate publication-ready LaTeX tables for the ICLR 2027 paper.

Table 1: Predictive capacity + Information-Bottleneck trade-offs for every
         cell of the dual-task matrix (model x prior x target), with the
         linear ridge tagged as the Optimal Regime and the LLM-gated
         transformer as the Bottleneck Zone (per the measured IB plane).
Table 2: Zero-shot LLM prior-generation provenance - the ACTUAL model read
         from each prior's provenance.json (never hard-coded), generation
         settings, prompt hash, and agreement with the Neurosynth
         working-memory reference map (Pearson r + top-10 overlap).

Outputs: outputs/iclr/tables/table1_ib_tradeoff.tex,
         outputs/iclr/tables/table2_prior_provenance.tex
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

DEFAULT_SUMMARY = "outputs/iclr/dual_task_matrix/summary.csv"
DEFAULT_TABLES = "outputs/iclr/tables"
NEUROSYNTH_WM = "outputs/priors/working_memory/aal116/roi_prior.csv"
PRIOR_ROOT = "outputs/priors/llm"

MODEL_NAMES = {
    "ncr": "Network-Constrained Ridge (linear)",
    "llm_gated": "LLM-Gated Transformer",
}
PRIOR_NAMES = {
    "llm_wm": "LLM WM (true)",
    "llm_fluid": "LLM Fluid (true)",
    "random_control": "Random control",
    "no_prior": "No prior",
}
TARGET_NAMES = {
    "fluid_intelligence": "Fluid Intell. ($\\mathrm{PMAT24}_{A\\_CR}$)",
    "working_memory": "Working Memory (ListSort)",
}


def _fmt(mean: float, std: float, digits: int = 3) -> str:
    return f"${mean:.{digits}f} \\pm {std:.{digits}f}$"


def make_table1(summary_csv: Path, splits_csv: Path | None = None) -> str:
    df = pd.read_csv(summary_csv)
    # Per-split selected-alpha distribution (Validation-Selected Discrete
    # Routing): most frequent alpha per cell + selection count.
    alpha_dist: dict[tuple, str] = {}
    if splits_csv is not None and Path(splits_csv).exists():
        sp = pd.read_csv(splits_csv)
        if "selected_alpha" in sp.columns and sp.selected_alpha.notna().any():
            for key, g in sp[sp.model == "llm_gated"].groupby(
                    ["prior", "target"]):
                counts = g.selected_alpha.value_counts()
                top_alpha, top_n = counts.index[0], int(counts.iloc[0])
                alpha_dist[(key[0], key[1])] = (
                    f"${top_alpha:.2f}$ ({top_n}/{len(g)})")
    else:
        for r in df.itertuples():
            if r.model == "llm_gated" and "selected_alpha_mean" in df.columns:
                if np.isfinite(getattr(r, "selected_alpha_mean", np.nan)):
                    alpha_dist[(r.prior, r.target)] = (
                        f"${r.selected_alpha_mean:.2f} \\pm "
                        f"{r.selected_alpha_std:.2f}$")
    required = {"model", "prior", "target", "pearson_mean", "pearson_std",
                "rmse_mean", "rmse_std", "I_XZ_final_mean", "I_XZ_final_std",
                "I_ZY_final_mean", "I_ZY_final_std"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"{summary_csv} missing {sorted(missing)}")

    order_m = {"ncr": 0, "llm_gated": 1}
    order_p = {"llm_wm": 0, "llm_fluid": 1, "random_control": 2, "no_prior": 3}
    order_t = {"fluid_intelligence": 0, "working_memory": 1}
    df["_o"] = (df.model.map(order_m) * 100 + df.prior.map(order_p) * 10
                + df.target.map(order_t))
    df = df.sort_values("_o")

    rows = []
    for r in df.itertuples():
        if r.model not in order_m or r.prior not in order_p or r.target not in order_t:
            continue
        regime = ("\\textbf{Optimal}" if r.model == "ncr"
                  else "Bottleneck zone")
        model_cell = (f"\\textbf{{{MODEL_NAMES[r.model]}}}"
                      if r.model == "ncr" else MODEL_NAMES[r.model])
        alpha_cell = alpha_dist.get((r.prior, r.target), "--")
        rows.append(
            f"{model_cell} & {PRIOR_NAMES[r.prior]} & {TARGET_NAMES[r.target]} & "
            f"{_fmt(r.pearson_mean, r.pearson_std)} & "
            f"{_fmt(r.rmse_mean, r.rmse_std)} & "
            f"{_fmt(r.I_XZ_final_mean, r.I_XZ_final_std)} & "
            f"{_fmt(r.I_ZY_final_mean, r.I_ZY_final_std)} & "
            f"{alpha_cell} & {regime} \\\\"
        )

    body = "\n".join(rows)
    return f"""% Generated by scripts/70_generate_iclr_latex_tables.py - DO NOT EDIT.
% Requires: \\usepackage{{booktabs}}
\\begin{{table*}}[t]
\\centering
\\small
\\caption{{Dual-task matrix (HCP-YA, $N=412$, nested CV): predictive capacity
and Information-Bottleneck trade-offs. $I(X;Z)$ (compression) and $I(Z;Y)$
(predictive capacity of the latent) are MINE-estimated in nats, averaged over
splits. The linear ridge operates in the \\textbf{{Optimal}} regime (low
compression, high predictive capacity); the LLM-gated transformer currently
sits in the Bottleneck Zone (high compression, low predictive capacity),
independent of prior type.}}
\\label{{tab:ib_tradeoff}}
\\resizebox{{\\textwidth}}{{!}}{{%
\\begin{{tabular}}{{lllcccccc}}
\\toprule
Model & Prior & Target & Pearson $r \\uparrow$ & RMSE $\\downarrow$ &
$I(X;Z) \\downarrow$ & $I(Z;Y) \\uparrow$ & Selected $\\alpha$ & Regime \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}}}
\\end{{table*}}
"""


def _prior_stats(path: Path, neuro: np.ndarray) -> dict:
    df = pd.read_csv(path).sort_values("roi_index")
    p = df.prior_score.to_numpy(np.float64)
    top10 = set(np.argsort(p)[-10:].tolist())
    neuro_top10 = set(np.argsort(neuro)[-10:].tolist())
    return {
        "top5": df.nlargest(5, "prior_score").roi_label.tolist(),
        "pearson_neuro": float(np.corrcoef(p, neuro)[0, 1]),
        "top10_overlap": len(top10 & neuro_top10),
    }


def make_table2(prior_root: Path,
                prior_slugs: tuple[tuple[str, str], ...]) -> tuple[str, str]:
    neuro_df = pd.read_csv(NEUROSYNTH_WM).sort_values("roi_index")
    neuro = neuro_df.prior_score.to_numpy(np.float64)

    rows = []
    actual_models = set()
    methods_seen = set()
    for slug, task in prior_slugs:
        pdir = prior_root / slug
        if not (pdir / "provenance.json").exists():
            print(f"[skip] {slug}: no provenance.json")
            continue
        prov = json.loads((pdir / "provenance.json").read_text())
        actual_models.add(str(prov["model"]))
        method = ("Contrastive"
                  if prov.get("prompting") == "contrastive" else "Zero-shot")
        methods_seen.add(method)
        stats = _prior_stats(pdir / "roi_prior.csv", neuro)
        rows.append(
            f"{task} & \\texttt{{{prov['model']}}} & {method} & "
            f"{prov['temperature']} & {prov['seed']} & "
            f"\\texttt{{{str(prov['prompt_sha256'])[:10]}}} & "
            f"{', '.join(stats['top5'][:3])}... & "
            f"{stats['pearson_neuro']:.2f} & {stats['top10_overlap']}/10 \\\\"
        )

    models_str = ", ".join(sorted(actual_models))
    methods_str = " + ".join(sorted(methods_seen)) or "Zero-shot"
    table = f"""% Generated by scripts/70_generate_iclr_latex_tables.py - DO NOT EDIT.
\\begin{{table}}[t]
\\centering
\\small
\\caption{{Zero-shot LLM semantic prior generation. Priors were produced by a
local foundation model served via Ollama (model and prompting method recorded
per prior in \\texttt{{provenance.json}}; actual model used:
\\texttt{{{models_str}}}; methods: {methods_str}), prompted with all 116 AAL
region labels and strict-JSON scoring instructions (three-tier JSON recovery;
no fine-tuning, no task training data shown). Contrastive rows add explicit
domain-exclusion criteria to break the Semantic-Blurring correlation between
adjacent cognitive domains. Agreement is measured against the Neurosynth
working-memory meta-analysis map.}}
\\label{{tab:prior_provenance}}
\\resizebox{{\\columnwidth}}{{!}}{{%
\\begin{{tabular}}{{llccclccc}}
\\toprule
Task & Model & Method & Temp & Seed & Prompt SHA & Top-3 regions &
$r$ vs Neurosynth & Top-10 overlap \\\\
\\midrule
{chr(10).join(rows)}
\\bottomrule
\\end{{tabular}}}}
\\end{{table}}
"""
    return table, models_str


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--summary", default=DEFAULT_SUMMARY)
    ap.add_argument("--splits", default=None,
                    help="split_metrics.csv for the selected-alpha "
                         "distribution column (Table 1)")
    ap.add_argument("--tables-dir", default=DEFAULT_TABLES)
    ap.add_argument("--prior-root", default=PRIOR_ROOT)
    ap.add_argument("--include-contrastive", action="store_true",
                    help="Also emit rows for *_contrastive_qwen3 priors "
                         "when present")
    args = ap.parse_args()

    out_dir = Path(args.tables_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    t1 = make_table1(Path(args.summary),
                     Path(args.splits) if args.splits else None)
    (out_dir / "table1_ib_tradeoff.tex").write_text(t1, encoding="utf-8")
    print(f"Wrote {out_dir / 'table1_ib_tradeoff.tex'}")

    slugs = [("working_memory", "Working Memory"),
             ("fluid_intelligence", "Fluid Intelligence")]
    if args.include_contrastive:
        slugs += [("working_memory_contrastive_qwen3", "Working Memory (contr.)"),
                  ("fluid_intelligence_contrastive_qwen3", "Fluid Intell. (contr.)")]
    t2, models = make_table2(Path(args.prior_root), tuple(slugs))
    (out_dir / "table2_prior_provenance.tex").write_text(t2, encoding="utf-8")
    print(f"Wrote {out_dir / 'table2_prior_provenance.tex'} "
          f"(actual generation model: {models})")


if __name__ == "__main__":
    main()
